version: "3"
services:
  app:
    container_name: app
    volumes:
      - ./:/app
    tty: true
    command: "air -c .air.toml"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:13.4
    ports:
      - '5432:5432'
    expose:
      - 5432
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: postgresql
      POSTGRES_PORT: 5432
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      TZ: "Asia/Tokyo"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
  log:
  tmp:
