version: "3"
services:
  app:
    container_name: app
    volumes:
      - ./:/app
    tty: true
    command: "air -c .air.toml"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080

