version: "3"
services:
  app:
    container_name: app
    volumes:
      - ./:/app
    tty: true
    command: "go run main.go"
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
