version: "3"
services:
  app:
    container_name: app
    volumes:
      - ./:/app
    tty: true
    command: "air -c .air.toml"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    container_name: db
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    ports:
      - '5432:5432'
    expose:
      - 5432
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_DB: golang_api
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: postgresql
      POSTGRES_PORT: 5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
