development:
  dialect: postgres
  datasource: host=db port=5432 dbname=api user=postgresql password=postgresql sslmode=disable # docker向け
  # datasource: host=localhost port=5432 dbname=api user=masahirookubo sslmode=disable # local向け
  dir: db/migrations
  table: migrations
